language: python
env:
  - ANSIBLE_VERSION="1.0.*"
  - ANSIBLE_VERSION="1.1.*"
  - ANSIBLE_VERSION="1.2.*"
  - ANSIBLE_VERSION="1.3.*"
  - ANSIBLE_VERSION="1.4.*"
  - ANSIBLE_VERSION="1.5.*"
  - ANSIBLE_VERSION="1.6.*"
  - ANSIBLE_VERSION="1.7.*"
  - ANSIBLE_VERSION="1.8.*"
  - ANSIBLE_VERSION="1.9.*"
install:
  - pip install ansible==$ANSIBLE_VERSION
  - sudo apt-get install supervisor
script:
  # Check the role syntax
  - ansible-playbook --inventory='localhost,' tests/test.yml --syntax-check
  # Check that the role can run with no errors/failures
  - ansible-playbook --inventory='localhost,' tests/test.yml --connection=local
  # Check idempotence of the role by running it twice and making sure there are
  # no changed/failed tasks
  - >
    ansible-playbook --inventory='localhost,' tests/test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

sudo: required
