---

# See https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories
- name: Ensure script to install NodeSource Node.js 0.12 repo has been executed
  shell: >
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    creates=/etc/apt/sources.list.d/nodesource.list
  sudo: yes

- name: Ensure Node.js 0.12 is installed
  apt:
    pkg: nodejs
    state: present
  sudo: yes

- name: Ensure Shout package is installed
  npm:
    name: shout
    global: yes
    production: yes
    version: 0.51.1
    state: present
  sudo: yes
