---

- name: Ensure Supervisor is installed
  apt:
    pkg: supervisor
    state: present
  become: yes

- name: Ensure script to install NodeSource Node.js 8.x repo has been executed
  shell:
    curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    creates=/etc/apt/sources.list.d/nodesource.list
  become: yes

- name: Ensure that the latest version of Node.js 8.x (LTS) is installed
  apt:
    pkg: nodejs
    state: latest
  become: yes

- name: Ensure thelounge package is installed
  npm:
    name: thelounge
    global: yes
    version: "{{ thelounge_version }}"
    state: present
  become: yes
  notify:
    - Restart supervisord program
    - Clean up npm temporary files

- name: Ensure user thelounge is present
  user:
    name: thelounge
    createhome: no
    comment: The Lounge (IRC client)
    system: yes
    state: present
  become: yes

- name: Ensure JS and JSON syntax checking packages are installed
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - esprima
    - jsonlint
  become: yes

- name: Retrieve the location of the global `node_modules` directory
  shell: npm list --global --parseable thelounge@{{ thelounge_version }}
  register: node_modules_path
  changed_when: False
  become: yes

- name: Ensure .thelounge_home points to the correct configuration directory
  copy:
    content: /etc/lounge/
    # Something like: /usr/lib/node_modules/thelounge/.thelounge_home
    dest: "{{ node_modules_path.stdout }}/.thelounge_home"
  become: yes
  notify: Restart supervisord program

- name: Ensure lounge configuration directory is present
  file:
    path: /etc/lounge
    owner: thelounge
    group: thelounge
    state: directory
  become: yes

- name: Ensure The Lounge is configured
  template:
    src: config.js.j2
    dest: /etc/lounge/config.js
    owner: thelounge
    group: thelounge
    validate: 'esvalidate %s'
  become: yes
  notify: Restart supervisord program

- name: Ensure user configuration directory is present
  file:
    path: /etc/lounge/users
    owner: thelounge
    group: thelounge
    state: directory
  become: yes
  notify: Restart supervisord program

- name: Ensure preview storage directory is present
  file:
    path: /etc/lounge/storage
    owner: thelounge
    group: thelounge
    mode: "0770"
    state: directory
  become: yes
  notify: Restart supervisord program

- name: Ensure user configuration files are present
  template:
    src: user.json.j2
    dest: /etc/lounge/users/{{ item.user }}.json
    owner: thelounge
    group: thelounge
    mode: "0660"
    force: no # Do not overwrite existing users to not erase networks
    validate: 'jsonlint -q %s'
  with_items: "{{ thelounge_users }}"
  become: yes
  notify: Restart supervisord program

- name: Ensure program configuration for supervisord is installed
  copy:
    src: lounge_supervisord.conf
    dest: /etc/supervisor/conf.d/lounge.conf
  become: yes
  notify: Restart supervisord program

- name: Ensure lounge supervisord program is present
  supervisorctl:
    name: lounge
    state: present
  become: yes
  notify: Restart supervisord program
