---

- name: Ensure Supervisor is installed
  apt:
    pkg: supervisor
    state: present
  sudo: yes

- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    force: yes
    state: present
  sudo: yes

- name: Ensure Nodesource apt key is present
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  sudo: yes

- name: Ensure NodeSource repositories for Node.js are present
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} wheezy main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} wheezy main"
  sudo: yes

# For example, 4.x becomes 4.* and matches 4.4.5-1nodesource1~wheezy1
- name: Ensure Node.js and npm are installed.
  apt:
    name: nodejs={{ nodejs_version|regex_replace('x', '') }}*
    state: present
    update_cache: yes
  sudo: yes

- name: Ensure thelounge package is installed
  npm:
    name: thelounge
    global: yes
    production: yes
    version: "{{ lounge_version }}"
    state: present
  sudo: yes
  notify:
    - Restart supervisord program
    - Clean up npm temporary files

- name: Ensure user lounge is present
  user:
    name: lounge
    createhome: no
    comment: The Lounge IRC
    system: yes
    state: present
  sudo: yes

- name: Ensure JS and JSON syntax checking packages are installed
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
    state: present
  with_items:
    - esprima
    - jsonlint
  sudo: yes

- name: Ensure lounge configuration directory is present
  file:
    path: /etc/lounge
    state: directory
  sudo: yes

- name: Ensure The Lounge is configured
  template:
    src: config.js
    dest: /etc/lounge/config.js
    validate: 'esvalidate %s'
  sudo: yes
  notify: Restart supervisord program

- name: Ensure user configuration directory is present
  file:
    path: /etc/lounge/users
    state: directory
  sudo: yes

- name: Ensure user configuration files are present
  template:
    src: user.json.j2
    dest: /etc/lounge/users/{{ item.user }}.json
    owner: lounge
    group: lounge
    mode: "0660"
    force: no # Do not overwrite existing users to not erase networks
    validate: 'jsonlint -q %s'
  with_items: lounge_users
  sudo: yes
  notify: Restart supervisord program

- name: Ensure program configuration for supervisord is installed
  copy:
    src: lounge_supervisord.conf
    dest: /etc/supervisor/conf.d/lounge.conf
  sudo: yes
  notify: Restart supervisord program

- name: Ensure lounge supervisord program is present
  supervisorctl:
    name: lounge
    state: present
  sudo: yes
  notify: Restart supervisord program
