---

- name: Ensure Supervisor is installed
  apt:
    pkg: supervisor
    state: present
  sudo: yes

# See https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories
- name: Ensure script to install NodeSource Node.js 0.12 repo has been executed
  shell:
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    creates=/etc/apt/sources.list.d/nodesource.list
  sudo: yes

- name: Ensure Node.js 0.12 is installed
  apt:
    pkg: nodejs
    state: present
  sudo: yes

- name: Ensure Shout package is installed
  npm:
    name: shout
    global: yes
    production: yes
    version: 0.51.2
    state: present
  sudo: yes
  notify: Restart supervisord program

- name: Ensure user shout is present
  user:
    name: shout
    createhome: no
    comment: Shout IRC
    system: yes
    state: present
  sudo: yes

- name: Ensure JS and JSON syntax checking packages are installed
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
    state: present
  with_items:
    - esprima
    - jsonlint
  sudo: yes

- name: Ensure Shout configuration directory is present
  file:
    path: /etc/shout
    state: directory
  sudo: yes

- name: Ensure Shout is configured
  template:
    src: config.js
    dest: /etc/shout/config.js
    validate: 'esvalidate %s'
  sudo: yes
  notify: Restart supervisord program

- name: Ensure user configuration directory is present
  file:
    path: /etc/shout/users
    state: directory
  sudo: yes

- name: Ensure user configuration files are present
  template:
    src: user.json.j2
    dest: /etc/shout/users/{{ item.user }}.json
    owner: shout
    group: shout
    mode: "0440"
    force: no # Do not overwrite existing users to not erase networks
    validate: 'jsonlint -q %s'
  with_items: shout_users
  sudo: yes
  notify: Restart supervisord program

- name: Ensure program configuration for supervisord is installed
  copy:
    src: shout_supervisord.conf
    dest: /etc/supervisor/conf.d/shout.conf
  sudo: yes
  notify: Restart supervisord program

- name: Ensure shout supervisord program is present
  supervisorctl:
    name: shout
    state: present
  sudo: yes
  notify: Restart supervisord program
