---

- name: Restart supervisord program
  supervisorctl:
    name: lounge
    state: restarted
  sudo: yes

- name: Clean up npm temporary files
  file:
    name: /tmp/npm-*
    state: absent
  sudo: yes
